### ISSUE TITLE
Specify the license clearer

### ISSUE THREAD

**Issue by ifraixedes** [rstacruz/unorphan#1]
Thanks for this nice npm module.

I've realised that is released under MIT, however the license only it's specified inside of `package.json` therefore it's hard to see it in a quick view.

If you don't mind, can you specify it in README or add a LICENSE file?

Thanks in advance.

**Comment by rstacruz** [comment]
Sure. Curious: why is this important to you?

**Comment by ifraixedes** [comment]
I've discovered it and I think that it can be useful.

When I discover new repositories, I always check the license, because not having one is totally wasted because for any personal or professional project I wouldn't never use them; it's not the case, but making it clearer can help others to decide to use for any project and grow the interest, popularity and you may get contributors to it.

In the time being, I don't plan to use, because I don't have any project where I need it, but I will bear in mind for future use cases which require this feature.

Thanks.

**Comment by rstacruz** [comment]
Ah, cool.

All my repositories have a "Released under MIT license" at the Readme footer, I was hoping that was enough for most cases, but every now and then people ask for a LICENSE file for legal reasons.

**Comment by ifraixedes** [comment]
Yep, I missed it, because it was under "Thanks" section; yeah with that was enough, sorry, I usually look for a License section, I hadn't seen it that you added under it, so I knew about the license of the `package.json`.

Thanks to add the License file, I think that it's clearer to find the license applied.
